DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS pet CASCADE;
DROP TABLE IF EXISTS zajavka_user_role CASCADE;
DROP TABLE IF EXISTS zajavka_user CASCADE;
DROP TABLE IF EXISTS zajavka_role CASCADE;
DROP TABLE IF EXISTS flyway_schema_history CASCADE;